sudo: required
services:
  - docker
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
language: rust
rust:
  - stable
before_script:
  - export RUST_BACKTRACE=full
script:
  - cargo clean
  - cargo build
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then cargo test; fi
  - cargo doc --no-deps
after_success: |
  if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    bash <(curl -sSL https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
notifications:
  email:
    on_success: change
    on_failure: always
branches:
  only:
    - "master"
