[package]
authors = ["Eirik Albrigtsen <ealbrigt@cisco.com>"]
name = "lal"
version = "0.29.0"

[[bin]]
doc = false
name = "lal"
path = "src/main.rs"

[dependencies]
ansi_term = "0.7.2"
chrono = "0.2"
clap = "*"
curl = "0.2.18"
filetime = "0.1"
flate2 = "0.2"
log = "0.3.5"
loggerv = "0.1.0"
regex = "0.1.55"
rustc-serialize = "0.3.18"
semver = "0.2.3"
tar = "0.4.4"
walkdir = "0.1.5"
rand = "0.3.14"

[lib]
name = "lal"
path = "src/lib.rs"

[[test]]
harness = false
name = "testmain"
